### ISSUE TITLE
运行pnpm run start报错怎么办啊

### ISSUE THREAD

**Issue by tinnnnnnny** [chatgpt-web-dev/chatgpt-web#141]
*  正在执行任务: pnpm run start 

> chatgpt-web-service@1.0.0 start C:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service
> esno ./src/index.ts

c:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:9
    return (connectionString.startsWith('mongodb://') ||
                             ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at connectionStringHasValidScheme (c:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:9:30)
    at ConnectionString (c:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service\node_modules\.pnpm\mongodb-connection-string-url@2.6.0\node_modules\mongodb-connection-string-url\lib\index.js:85:34)
    at parseOptions (c:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\connection_string.js:204:17)
    at MongoClient (c:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service\node_modules\.pnpm\mongodb@5.1.0\node_modules\mongodb\lib\mongo_client.js:46:50)
    at <anonymous> (c:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service\src\storage\mongo.ts:9:16)
    at Object.<anonymous> (c:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service\src\storage\mongo.ts:202:23)       
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.F (C:\Users\lingkai\Desktop\chatgpt-web-2.12.6\service\node_modules\.pnpm\@esbuild-kit+cjs-loader@2.4.2\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.

求助各位

**Comment by qsc19971022** [comment]
mongo地址有问题把

**Comment by tinnnnnnny** [comment]
> mongo地址有问题把

我没有安装过mongo... 教程里没有说要安装啊 在哪里修改地址啊= =

**Comment by Kerwin1202** [comment]
执行之前需要把service 目录下的 .env.example 重命名为 .env 然后 里面的配置修改下 设置好再试试

**Comment by vintonHuang** [comment]
前端和后端服务都运行起来了，为什么/api/session 报错
<img width="546" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/45648362/ba66dcdd-7b24-4b1e-a006-9527e06c5224">

**Comment by Kerwin1202** [comment]
看不出

> 前端和后端服务都运行起来了，为什么/api/session 报错 <img alt="image" width="546" src="https://user-images.githubusercontent.com/45648362/242147599-ba66dcdd-7b24-4b1e-a006-9527e06c5224.png">

**Comment by SongDI911** [comment]
> 前端和后端服务都运行起来了，为什么/api/session 报错 <img alt="image" width="546" src="https://private-user-images.githubusercontent.com/45648362/242147599-ba66dcdd-7b24-4b1e-a006-9527e06c5224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ5Njg2MDEsIm5iZiI6MTc0NDk2ODMwMSwicGF0aCI6Ii80NTY0ODM2Mi8yNDIxNDc1OTktYmE2NmRjZGQtN2IyNC00YjFlLWEwMDYtOTUyN2UwNmM1MjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE4VDA5MjUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNzA1YTU4NDdlMGI2M2RjNmIwMGQwZDZmODU4Njc4OWM1N2ZlOGJmZWUwZDRmOGMxOTc4YmI4OTk1NmVhMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0ruFoYJNeYvteMDYY-mpHY1NjR5IdzQXzadIbIrxILs">

数据库没连上
